Add bootloader installation service
This is used by the build system.

Signed-off-by: Colin Walters <walters@verbum.org>

diff --git a/src/installboot/gnome-ostree-install-boot b/src/installboot/gnome-ostree-install-boot
--- a/src/installboot/gnome-ostree-install-boot
+++ b/src/installboot/gnome-ostree-install-boot
@@ -1,4 +1,5 @@
-# Copyright (C) 2011 Colin Walters <walters@verbum.org>
+#!/bin/sh
+# Install extlinux on the currently active root device
 #
 # This library is free software; you can redistribute it and/or
 # modify it under the terms of the GNU Lesser General Public
@@ -15,29 +16,14 @@
 # Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 # Boston, MA 02111-1307, USA.
 
-ACLOCAL_AMFLAGS = -I m4 ${ACLOCAL_FLAGS}
-AM_CPPFLAGS = -DDATADIR='"$(datadir)"' -DLIBEXECDIR='"$(libexecdir)"'
-AM_CFLAGS = $(WARN_CFLAGS)
+set -e
 
-NULL = 
-BUILT_SOURCES =
-MANPAGES =
-CLEANFILES =
-EXTRA_DIST =
-bin_PROGRAMS =
-sbin_PROGRAMS =
-bin_SCRIPTS =
-libexec_PROGRAMS =
-noinst_LTLIBRARIES =
-noinst_PROGRAMS =
-privlibdir = $(pkglibdir)
-privlib_LTLIBRARIES =
-INSTALL_DATA_HOOKS =
+export BOOT_PARTITION=`cat /proc/mounts | tr -s " " | grep /boot | cut -d " " -f 1 | sed "s, ,,g"`
+export DEVICE=`echo ${BOOT_PARTITION} | sed -rn "s,(.+)([0-9]),\1,p"`
+export PARTITION=`echo ${BOOT_PARTITION} | sed -rn "s,(.+)([0-9]),\2,p"`
 
-include Makefile-integration.am
-include Makefile-installboot.am
+if test -z "${DEVICE}"; then echo "Failed to determine device"; exit 1; fi
 
-install-data-hook: $(INSTALL_DATA_HOOKS)
-
-release-tag:
-	git tag -m "Release $(VERSION)" v$(VERSION)
+dd if=/usr/lib/syslinux/mbr.bin of=${DEVICE}
+/usr/sbin/extlinux --install /boot/
+systemctl poweroff
